### PR TITLE
Revert "support Iris driver"

### PR DESCRIPTION
**Pull request by renchenglei**
This reverts commit 9cc7cdc490349db1fa7abd83c85223bcfe5e8cc1.

### CODE REVIEW

**Comment by renchenglei** [comment]
@Shao-Feng & @feijiang1  & @YuanjunHuang 
Could you help take a review of this changes? Same HWC changes for celadon, thanks a lot!

**Review by feijiang1 — APPROVED** [review]

**Comment by Shao-Feng** [comment]
Did you ever ping @tpalli for this issue?

**Comment by tpalli** [comment]
This is fine, iris should work well on Android now with explicit sync. This is of course assuming the Mesa sources are recent enough to have the fixes in place. Let me know if there is any trouble and we can figure out what fixes would be missing.

**Comment by renchenglei** [comment]
> This is fine, iris should work well on Android now with explicit sync. This is of course assuming the Mesa sources are recent enough to have the fixes in place. Let me know if there is any trouble and we can figure out what fixes would be missing.

Thanks @tpalli! Currently, the mesa version is 20.2.3 on Celadon, we will keep monitor if there is issue on TGL, : )

**Pull request merged**
